// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wallet} from '../models';
import {main} from '../models';

export function CreateDirectory(arg1:string):Promise<boolean>;

export function GenerateAccount(arg1:string):Promise<wallet.Wallet>;

export function IpfsRun():void;

export function StopIPFS():Promise<boolean>;

export function AddFile(arg1:string,arg2:string):Promise<boolean>;

export function GetAccount(arg1:string):Promise<Array<wallet.Wallet>>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function TransferFunds():void;

export function GenerateWallet():Promise<main.Wallet>;

export function OpenMessage():void;

export function GetBalance(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ReadDirectory(arg1:string):Promise<number>;

export function RemoveFile(arg1:string):Promise<boolean>;

export function StartIPFS():Promise<number>;

export function Connect():Promise<string>;
