// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFile(arg1, arg2) {
  return window['go']['main']['App']['AddFile'](arg1, arg2);
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function DecryptData(arg1) {
  return window['go']['main']['App']['DecryptData'](arg1);
}

export function EncryptToSmart(arg1, arg2) {
  return window['go']['main']['App']['EncryptToSmart'](arg1, arg2);
}

export function FileStat() {
  return window['go']['main']['App']['FileStat']();
}

export function GenerateAccount(arg1) {
  return window['go']['main']['App']['GenerateAccount'](arg1);
}

export function GenerateWallet() {
  return window['go']['main']['App']['GenerateWallet']();
}

export function GetAccount(arg1) {
  return window['go']['main']['App']['GetAccount'](arg1);
}

export function GetAccountExist() {
  return window['go']['main']['App']['GetAccountExist']();
}

export function GetBalance(arg1) {
  return window['go']['main']['App']['GetBalance'](arg1);
}

export function GetIPFS(arg1) {
  return window['go']['main']['App']['GetIPFS'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IpfsRun() {
  return window['go']['main']['App']['IpfsRun']();
}

export function OpenMessage() {
  return window['go']['main']['App']['OpenMessage']();
}

export function ReadDirectory(arg1) {
  return window['go']['main']['App']['ReadDirectory'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RemoveFile(arg1) {
  return window['go']['main']['App']['RemoveFile'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function StartIPFS() {
  return window['go']['main']['App']['StartIPFS']();
}

export function StopIPFS() {
  return window['go']['main']['App']['StopIPFS']();
}

export function TransferFunds() {
  return window['go']['main']['App']['TransferFunds']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
